name: test

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
  
jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Annotate
        uses: derigel23/ReSharper-InspectCode@6fceb504ae742791a488a414d44a59873a268500
        with:
          solution: RaidBattlesBot.sln
          tool-version: 2023.1.2
          format: Text
